version: 1.0.1.{build}

build: off
test: off

assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'

install:
  - ps: scripts\pre-build.ps1

build_script:
  - cmd: build.cmd
  
artifacts:
  - path: artifacts\Release\_PublishedWebsites\Geveze.Web
    name: Geveze.Web
    type: zip
  - path: artifacts\Geveze.*.nupkg
    name: GevezeDb